import type {
    Supplier,
    Alert,
    RiskTrend,
    RegionRisk,
    SavingsMetric,
    DashboardStats,
} from "./types";

// ─── Suppliers ────────────────────────────────────────────────────────────────

export const SUPPLIERS: Supplier[] = [
    {
        id: "sup_001",
        name: "Shenzhen TechParts Co.",
        country: "China",
        countryCode: "CN",
        region: "asia",
        category: "Semiconductors",
        components: ["MCU chips", "MOSFET transistors", "Capacitors"],
        riskScore: 87,
        riskLevel: "critical",
        status: "disrupted",
        lastUpdated: "2026-03-05T17:30:00Z",
        contactName: "Wei Zhang",
        contactEmail: "w.zhang@sztechparts.cn",
        tier: 1,
        annualSpend: 2400000,
        lat: 22.54,
        lng: 114.07,
        trend: "up",
        alerts: 4,
    },
    {
        id: "sup_002",
        name: "Munich Precision GmbH",
        country: "Germany",
        countryCode: "DE",
        region: "europe",
        category: "Mechanical Parts",
        components: ["CNC housings", "Aluminum extrusions", "Fasteners"],
        riskScore: 34,
        riskLevel: "low",
        status: "active",
        lastUpdated: "2026-03-05T16:15:00Z",
        contactName: "Klaus Weber",
        contactEmail: "k.weber@munich-precision.de",
        tier: 1,
        annualSpend: 1800000,
        lat: 48.14,
        lng: 11.58,
        trend: "stable",
        alerts: 0,
    },
    {
        id: "sup_003",
        name: "Osaka Electronics Ltd.",
        country: "Japan",
        countryCode: "JP",
        region: "asia",
        category: "Displays",
        components: ["OLED panels", "LCD modules", "Touchscreens"],
        riskScore: 62,
        riskLevel: "high",
        status: "at_risk",
        lastUpdated: "2026-03-05T15:45:00Z",
        contactName: "Yuki Tanaka",
        contactEmail: "y.tanaka@osaka-elec.jp",
        tier: 1,
        annualSpend: 3100000,
        lat: 34.69,
        lng: 135.5,
        trend: "up",
        alerts: 2,
    },
    {
        id: "sup_004",
        name: "Seoul Chip Foundry",
        country: "South Korea",
        countryCode: "KR",
        region: "asia",
        category: "Semiconductors",
        components: ["DDR5 RAM", "NAND Flash", "SSD controllers"],
        riskScore: 71,
        riskLevel: "high",
        status: "at_risk",
        lastUpdated: "2026-03-05T14:20:00Z",
        contactName: "Ji-ho Park",
        contactEmail: "jiho.park@seoulchip.kr",
        tier: 1,
        annualSpend: 4200000,
        lat: 37.56,
        lng: 126.98,
        trend: "up",
        alerts: 3,
    },
    {
        id: "sup_005",
        name: "Amsterdam Logistics BV",
        country: "Netherlands",
        countryCode: "NL",
        region: "europe",
        category: "Logistics",
        components: ["Freight forwarding", "Last-mile delivery", "Customs clearance"],
        riskScore: 28,
        riskLevel: "low",
        status: "active",
        lastUpdated: "2026-03-05T13:00:00Z",
        contactName: "Emma de Vries",
        contactEmail: "e.devries@amshipping.nl",
        tier: 2,
        annualSpend: 980000,
        lat: 52.37,
        lng: 4.9,
        trend: "stable",
        alerts: 0,
    },
    {
        id: "sup_006",
        name: "Bangalore PCB Works",
        country: "India",
        countryCode: "IN",
        region: "asia",
        category: "PCB Manufacturing",
        components: ["Multilayer PCBs", "Flex PCBs", "PCB Assembly"],
        riskScore: 55,
        riskLevel: "medium",
        status: "active",
        lastUpdated: "2026-03-05T12:30:00Z",
        contactName: "Priya Sharma",
        contactEmail: "p.sharma@blrpcb.in",
        tier: 2,
        annualSpend: 760000,
        lat: 12.97,
        lng: 77.6,
        trend: "down",
        alerts: 1,
    },
    {
        id: "sup_007",
        name: "Guadalajara Electronics MX",
        country: "Mexico",
        countryCode: "MX",
        region: "americas",
        category: "Contract Manufacturing",
        components: ["PCB Assembly", "Final assembly", "Testing"],
        riskScore: 43,
        riskLevel: "medium",
        status: "active",
        lastUpdated: "2026-03-05T11:45:00Z",
        contactName: "Carlos Mendez",
        contactEmail: "c.mendez@guadaelec.mx",
        tier: 2,
        annualSpend: 1350000,
        lat: 20.66,
        lng: -103.35,
        trend: "down",
        alerts: 1,
    },
    {
        id: "sup_008",
        name: "Taipei Connector Corp",
        country: "Taiwan",
        countryCode: "TW",
        region: "asia",
        category: "Connectors",
        components: ["USB-C connectors", "HDMI ports", "Board-to-board connectors"],
        riskScore: 79,
        riskLevel: "high",
        status: "at_risk",
        lastUpdated: "2026-03-05T10:00:00Z",
        contactName: "Mei-Ling Chen",
        contactEmail: "m.chen@taipeiconn.tw",
        tier: 1,
        annualSpend: 890000,
        lat: 25.05,
        lng: 121.52,
        trend: "up",
        alerts: 2,
    },
    {
        id: "sup_009",
        name: "Ho Chi Minh Assembly Co.",
        country: "Vietnam",
        countryCode: "VN",
        region: "asia",
        category: "Contract Manufacturing",
        components: ["Cable assemblies", "Wire harnesses", "Sub-assemblies"],
        riskScore: 38,
        riskLevel: "low",
        status: "active",
        lastUpdated: "2026-03-04T18:00:00Z",
        contactName: "Nguyen Van Minh",
        contactEmail: "n.v.minh@hcmassembly.vn",
        tier: 2,
        annualSpend: 620000,
        lat: 10.82,
        lng: 106.63,
        trend: "stable",
        alerts: 0,
    },
    {
        id: "sup_010",
        name: "Rotterdam Freight Services",
        country: "Netherlands",
        countryCode: "NL",
        region: "europe",
        category: "Logistics",
        components: ["Ocean freight", "Port handling", "Warehousing"],
        riskScore: 18,
        riskLevel: "none",
        status: "active",
        lastUpdated: "2026-03-04T16:00:00Z",
        contactName: "Hendrik Mulder",
        contactEmail: "h.mulder@rtmfreight.nl",
        tier: 3,
        annualSpend: 440000,
        lat: 51.92,
        lng: 4.48,
        trend: "stable",
        alerts: 0,
    },
    {
        id: "sup_011",
        name: "Chennai Battery Systems",
        country: "India",
        countryCode: "IN",
        region: "asia",
        category: "Energy Storage",
        components: ["Li-ion cells", "BMS modules", "Battery packs"],
        riskScore: 48,
        riskLevel: "medium",
        status: "active",
        lastUpdated: "2026-03-05T09:00:00Z",
        contactName: "Arjun Nair",
        contactEmail: "a.nair@chennaibat.in",
        tier: 2,
        annualSpend: 1100000,
        lat: 13.08,
        lng: 80.27,
        trend: "stable",
        alerts: 1,
    },
    {
        id: "sup_012",
        name: "Kuala Lumpur Sensors Sdn.",
        country: "Malaysia",
        countryCode: "MY",
        region: "asia",
        category: "Sensors & ICs",
        components: ["MEMS sensors", "Pressure sensors", "Analog ICs"],
        riskScore: 91,
        riskLevel: "critical",
        status: "disrupted",
        lastUpdated: "2026-03-05T18:00:00Z",
        contactName: "Ahmad Razali",
        contactEmail: "a.razali@klsensors.my",
        tier: 1,
        annualSpend: 1750000,
        lat: 3.14,
        lng: 101.69,
        trend: "up",
        alerts: 5,
    },
];

// ─── Alerts ───────────────────────────────────────────────────────────────────

export const ALERTS: Alert[] = [
    {
        id: "alt_001",
        supplierId: "sup_012",
        supplierName: "Kuala Lumpur Sensors Sdn.",
        type: "weather",
        severity: "critical",
        title: "Typhoon Alert – Factory Closure Imminent",
        description:
            "Category 4 typhoon tracking directly over Kuala Lumpur manufacturing district. Estimated factory closure of 72–120 hours. Expedite alternative sourcing immediately.",
        timestamp: "2026-03-05T17:45:00Z",
        predictedImpact: 380000,
        probability: 94,
        timeToImpact: 18,
        resolved: false,
        region: "Southeast Asia",
        acknowledged: false,
    },
    {
        id: "alt_002",
        supplierId: "sup_001",
        supplierName: "Shenzhen TechParts Co.",
        type: "geopolitical",
        severity: "critical",
        title: "Trade Restriction – Semiconductor Export Controls",
        description:
            "New US-China export control measures effective in 48 hours may restrict MCU chip shipments. Estimated 60% probability of supply halt for Q2 orders.",
        timestamp: "2026-03-05T15:30:00Z",
        predictedImpact: 520000,
        probability: 88,
        timeToImpact: 48,
        resolved: false,
        region: "East Asia",
        acknowledged: true,
    },
    {
        id: "alt_003",
        supplierId: "sup_004",
        supplierName: "Seoul Chip Foundry",
        type: "labor",
        severity: "high",
        title: "Labor Strike – Production at 40% Capacity",
        description:
            "Union dispute at Seoul Chip Foundry has reduced production capacity to 40%. DDR5 RAM and NAND Flash deliveries delayed 2–3 weeks. Escalation risk: 71%.",
        timestamp: "2026-03-05T12:00:00Z",
        predictedImpact: 210000,
        probability: 71,
        timeToImpact: 72,
        resolved: false,
        region: "East Asia",
        acknowledged: false,
    },
    {
        id: "alt_004",
        supplierId: "sup_003",
        supplierName: "Osaka Electronics Ltd.",
        type: "logistics",
        severity: "high",
        title: "Port Congestion – 14-Day Shipping Delay",
        description:
            "Port of Osaka experiencing severe congestion due to equipment failure. OLED panel deliveries face 14-day delays. Airfreight alternative costs $45k/container.",
        timestamp: "2026-03-05T09:15:00Z",
        predictedImpact: 145000,
        probability: 82,
        timeToImpact: 96,
        resolved: false,
        region: "East Asia",
        acknowledged: true,
    },
    {
        id: "alt_005",
        supplierId: "sup_008",
        supplierName: "Taipei Connector Corp",
        type: "geopolitical",
        severity: "high",
        title: "Regional Tensions Elevate Shipping Risk",
        description:
            "Escalating Taiwan Strait tensions have increased maritime insurance premiums 23% and some carriers are rerouting. Monitor shipment ETA adjustments closely.",
        timestamp: "2026-03-04T22:00:00Z",
        predictedImpact: 89000,
        probability: 65,
        timeToImpact: 120,
        resolved: false,
        region: "East Asia",
        acknowledged: false,
    },
    {
        id: "alt_006",
        supplierId: "sup_006",
        supplierName: "Bangalore PCB Works",
        type: "financial",
        severity: "medium",
        title: "Currency Volatility – Cost Increase Signal",
        description:
            "INR/USD depreciation of 4.2% this week is affecting invoice prices. Current 30-day term contracts may be renegotiated upward by 5–8%.",
        timestamp: "2026-03-04T14:30:00Z",
        predictedImpact: 42000,
        probability: 55,
        timeToImpact: 240,
        resolved: false,
        region: "South Asia",
        acknowledged: true,
    },
    {
        id: "alt_007",
        supplierId: "sup_007",
        supplierName: "Guadalajara Electronics MX",
        type: "logistics",
        severity: "medium",
        title: "Border Delay – US-Mexico Cross-Border Inspection",
        description:
            "Enhanced CBP inspections at Laredo crossing are adding 3–5 day delays. PCB assemblies in transit currently held for secondary inspection.",
        timestamp: "2026-03-04T11:00:00Z",
        predictedImpact: 31000,
        probability: 60,
        timeToImpact: 72,
        resolved: false,
        region: "Americas",
        acknowledged: false,
    },
    {
        id: "alt_008",
        supplierId: "sup_011",
        supplierName: "Chennai Battery Systems",
        type: "weather",
        severity: "medium",
        title: "Monsoon Season – Logistics Risk Window",
        description:
            "Early monsoon forecast for Chennai region may disrupt road logistics for 3–4 weeks starting late March. Pre-position inventory recommended.",
        timestamp: "2026-03-03T08:00:00Z",
        predictedImpact: 67000,
        probability: 48,
        timeToImpact: 336,
        resolved: false,
        region: "South Asia",
        acknowledged: true,
    },
];

// ─── Risk trend data ──────────────────────────────────────────────────────────

export const RISK_TRENDS: RiskTrend[] = [
    { date: "Feb 06", critical: 1, high: 3, medium: 4, low: 5 },
    { date: "Feb 13", critical: 2, high: 4, medium: 3, low: 4 },
    { date: "Feb 20", critical: 1, high: 3, medium: 5, low: 4 },
    { date: "Feb 27", critical: 2, high: 5, medium: 4, low: 3 },
    { date: "Mar 05", critical: 2, high: 3, medium: 3, low: 4 },
];

// ─── Region risk breakdown ────────────────────────────────────────────────────

export const REGION_RISKS: RegionRisk[] = [
    { region: "East Asia", suppliers: 5, avgRisk: 78, disruptions: 4 },
    { region: "Southeast Asia", suppliers: 3, avgRisk: 61, disruptions: 2 },
    { region: "Europe", suppliers: 3, avgRisk: 27, disruptions: 0 },
    { region: "South Asia", suppliers: 3, avgRisk: 47, disruptions: 1 },
    { region: "Americas", suppliers: 1, avgRisk: 43, disruptions: 1 },
];

// ─── Monthly savings data ─────────────────────────────────────────────────────

export const SAVINGS_DATA: SavingsMetric[] = [
    { month: "Oct", avoided: 82000, actual: 12000 },
    { month: "Nov", avoided: 134000, actual: 8000 },
    { month: "Dec", avoided: 91000, actual: 22000 },
    { month: "Jan", avoided: 167000, actual: 5000 },
    { month: "Feb", avoided: 203000, actual: 18000 },
    { month: "Mar", avoided: 142000, actual: 9000 },
];

// ─── Dashboard stats ──────────────────────────────────────────────────────────

export const DASHBOARD_STATS: DashboardStats = {
    totalSuppliers: 12,
    activeAlerts: 8,
    criticalAlerts: 2,
    avgRiskScore: 54.5,
    disruptionsAvoided: 23,
    savingsThisMonth: 142000,
    savingsTotal: 819000,
    uptimePercent: 99.97,
};

// ─── Alternative suppliers ────────────────────────────────────────────────────

export const ALTERNATIVE_SUPPLIERS = [
    {
        id: "alt_sup_001",
        name: "Bangkok Semiconductor Co.",
        country: "Thailand",
        category: "Semiconductors",
        ratingScore: 82,
        leadTimeDays: 14,
        costDelta: "+8%",
        verified: true,
    },
    {
        id: "alt_sup_002",
        name: "Ho Chi Minh Sensors Ltd.",
        country: "Vietnam",
        category: "Sensors & ICs",
        ratingScore: 76,
        leadTimeDays: 21,
        costDelta: "+4%",
        verified: true,
    },
    {
        id: "alt_sup_003",
        name: "Penang Electronics Hub",
        country: "Malaysia",
        category: "Semiconductors",
        ratingScore: 89,
        leadTimeDays: 10,
        costDelta: "+12%",
        verified: true,
    },
    {
        id: "alt_sup_004",
        name: "Gujarat Sensor Works",
        country: "India",
        category: "Sensors & ICs",
        ratingScore: 71,
        leadTimeDays: 18,
        costDelta: "-3%",
        verified: false,
    },
];
